#!/usr/bin/env bash

# Delete all JS templates to start fresh
rm -rf packages/cli/src/generator_templates/js/emails

# Generate JS templates from TS Templates
npx tsc \
--allowSyntheticDefaultImports true \
--moduleResolution node \
--jsx preserve \
--target es2020 \
--outDir packages/cli/src/generator_templates/js/emails \
--noEmit false \
packages/cli/src/generator_templates/ts/emails/**/*.tsx packages/cli/src/generator_templates/ts/emails/*.ts

# Format the generated JS templates
npx prettier --write packages/cli/src/generator_templates/js/*
yarn eslint --fix --ext .jsx,.js packages/cli/src/generator_templates/js/*

# Add the generated JS templates to git
git add packages/cli/src/generator_templates/js/*
