#!/usr/bin/env bash

# Generate JS templates from TS Templates
npx tsc \
--allowSyntheticDefaultImports true \
--moduleResolution node \
--jsx preserve \
--target es2020 \
--outDir packages/cli/src/emails-js \
--noEmit false \
packages/cli/src/emails/**/*.tsx \
packages/cli/src/emails/*.tsx \
packages/cli/src/emails/*.ts

# Format the generated JS templates
npx prettier --write packages/cli/src/emails-js/*
yarn eslint --fix --ext .jsx,.js packages/cli/src/emails-js/*

# Add the generated JS templates to git
git add packages/cli/src/emails-js/*