#! /bin/sh

yarn build

export PATH="$(yarn global bin):$PATH"

cd packages/core
yalc publish
cd -

cd packages/cli
yalc publish
cd -

rm -rf dev-app
cp -R packages/cli/src/generator_templates/ts/mailing-test-nextjs dev-app
cd dev-app
yarn
yalc add mailing-core
yalc add mailing
MM_VERBOSE=1 mailing &
open http://localhost:3000/api/hello
yarn dev # start the nextjs demo app
