#! /bin/sh

yarn build

export PATH="$(yarn global bin):$PATH"

cd packages/core
yarn unlink && yarn link
cd -

cd packages/cli
yarn unlink && yarn link
cd -

rm -rf dev-app
cp -R packages/cli/src/generator_templates/ts/mailing-test-nextjs dev-app
cd dev-app
yarn
yarn link mailing-core
yarn link mailing
mailing &
open http://localhost:3000/api/hello
yarn dev
